# Generated by Django 3.1.4 on 2020-12-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20201202_1158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
